server:
  port: 3344


spring:
  application:
    name: cloud-config-center          #注册进Eureka服务器的服务名

  cloud:
    config:
      server:
        git:
          uri: https://github.com/OuyangKe999/springcloud-config.git     #GitHub上面的git仓库名字  https协议
          #搜索目录
          search-paths:
            -springcloud-config
      #读取分支
      label: master

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true.单节点无所谓。集群必须设置为true才能配合Ribbon使用负责均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka 单机版
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
      defaultZone: http://eureka7001.com:7001/eureka/


#RabbitMQ相关配置
rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


#RabbitMQ相关配置,暴露bus刷新配置的端点
management:
  endpoint: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'
