server:
  port: 9527

spring:
  application:
    name: cloud-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true                               #开启从注册中心动态创建路由的功能，利用微服务名进行路由 uri协议为：lb 实现负载均衡
      routes:
        - id: payment_routh  #payment_route           #路由的ID，没有固定规则但要求唯一，建议配合服务名
         # uri: http://localhost:8001                  #匹配后提供服务的路由地址

          uri: lb://CLOUD-PAYMENT-SERVICE              #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**                    #断言，路径相匹配的进行路由

        - id: payment_routh2  #payment_route           #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001                  #匹配后提供服务的路由地址

          uri: lb://CLOUD-PAYMENT-SERVICE              #匹配后提供服务的路由地址  集群

          predicates:
            - Path=/payment/lb/**                    #断言，路径相匹配的进行路由
            - After=2020-07-25T02:21:23.487+08:00[Asia/Shanghai]  #这个时间后才能访问
           # - Before=2020-07-25T03:21:23.487+08:00[Asia/Shanghai] #这个时间前能访问
           # - Between=2020-07-25T02:21:23.487+08:00[Asia/Shanghai],2020-07-25T03:21:23.487+08:00[Asia/Shanghai]  #时间之间才能访问
           # - Cookie=username,oyk  #相当于KV键值对， 第一个是Cookie name ,第二个是正则表达式   cmd测试：curl http://localhost:9527/payment/lb --cookie "username=oyk"
           # - Header=X-Request-Id, \d+               #请求头要有X-Request-Id属性并且值为整数的正则表达式  curl http://localhost:9527/payment/lb -H “X-Request-Id:1234”
           # - Query=username,  \d+   #要有参数名username并且值还要是整数才能路由   http://localhost:9527/payment/lb?username=31

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true.单节点无所谓。集群必须设置为true才能配合Ribbon使用负责均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka 单机版
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
      defaultZone: http://eureka7001.com:7001/eureka/